name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build 1.16-alpine
      run: docker build . --file ./docker/1.16-alpine/Dockerfile --tag cn007b/go:1.16-alpine-$(date +%s)
    - name: Build 1.17-alpine
      run: docker build . --file ./docker/1.17-alpine/Dockerfile --tag cn007b/go:1.17-alpine-$(date +%s)
