name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

defaults:
  run:
    working-directory: .

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build 1.16-alpine
      run: docker build . -f ./docker/1.16-alpine/Dockerfile -t cn007b/go:1.16-alpine-$(date +%s)
    - name: Build 1.17-alpine
      run: docker build . -f ./docker/1.17-alpine/Dockerfile -t cn007b/go:1.17-alpine-$(date +%s)

  push_to_gcr:
    name: Push to GCR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          export_default_credentials: true
      - name: Build
        run: |-
          docker build . --file ./docker/1.17-alpine/Dockerfile -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/go:1.17-alpine
      - run: |
          gcloud auth configure-docker -q
      - name: Push
        run: |-
          docker push eu.gcr.io/${{ secrets.GCP_PROJECT_ID }}/go:1.17-alpine
